import pkg from '../package.json';

export const nextSeoConfig = {
  title: pkg.title,
  description: pkg.description,
  canonical: 'https://www.clydeventures.com/',
  keywords: [
    'consultancy',
    'consult',
    'consultation',
    'manufacture',
    'manufacturing',
    'manufacturer',
    'FRP',
    'Fibre reinforced polymers',
    'Fire doors',
    'Fire panels',
    'Fire cladding',
    'integration',
    'systems integration',
    'automation',
    'CRM',
    'Education',
    'Educate',
    'Sustainability MBA',
    'Diversity recruitment',
    'Glasgow consultancy',
    'Glasgow systems integrations',
    'Salesforce, energy consultancy',
    'regulatory consultancy',
    'salesforce consultancy',
    'Digital transformation',
    'Price cap',
    'Net Zero',
    'Price Control',
    'Digital transformation',
  ],
  icon: '/favicon.ico',
  themeColor: '#f9c156',
  colorScheme: 'light',
  facebook: {
    image: '/og-logo.png',
    url: 'https://clydeventures.com',
    type: 'website',
  },
  twitter: {
    image: 'https://www.clydeventures.com/1.png',
    site: '@clydeventures',
    card: 'summary',
  },
};
